TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 32
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR: ../video_dataset/
  NUM_FRAMES: 8
  SAMPLING_RATE: 32
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]

SOLVER:
  BASE_LR: 0.05
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 18, 25]
  LRS: [1 ,0.6 ,0.2]
  MAX_EPOCH: 50 #接着训练，在此基础上加上训练的轮数，上一次训练了10次，如果再训练5次，调整为15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: MLPMixerModel
  NUM_CLASSES: 94
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 3407

TENSORBOARD:
  ENABLE: True
  LOG_DIR: tensorboard/log
  # Leave empty to use cfg.OUTPUT_DIR/runs-{cfg.TRAIN.DATASET} as path.
  CLASS_NAMES_PATH: tensorboard/class_name_last.json
  # Path to json file providing class_name - id mapping.
  CATEGORIES_PATH: tensorboard/parent_child_last.json
  CONFUSION_MATRIX:
    ENABLE: True
    SUBSET_PATH: tensorboard/subset_last.txt
    # Path to txt file contains class names separated by newline characters.
                 # Only classes in this file will be visualized in the confusion matrix.
  HISTOGRAM:
    ENABLE: True
    TOPK: 5   
    # Top-k most frequently predicted classes for each class in the dataset.
    SUBSET_PATH: tensorboard/subset_last.txt
    # Path to txt file contains class names separated by newline characters.
                 # Only classes in this file will be visualized with histograms.


OUTPUT_DIR: result/mlp/
