TRAIN:
  # ENABLE: False # default True
  DATASET: kinetics
  BATCH_SIZE: 16
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 5.0
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 16
  # CHECKPOINT_FILE_PATH: 'x3d_l.pyth' # 77.48% top1 30-view accuracy to download from the model zoo (optional).
  # NUM_SPATIAL_CROPS: 1
  NUM_SPATIAL_CROPS: 3
DATA:
  PATH_TO_DATA_DIR: ../video_dataset/
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [356, 446]
  TRAIN_CROP_SIZE: 312
  # TEST_CROP_SIZE: 312 # use if TEST.NUM_SPATIAL_CROPS: 1
  TEST_CROP_SIZE: 356 # use if TEST.NUM_SPATIAL_CROPS: 3
  INPUT_CHANNEL_NUM: [3]
  DECODING_BACKEND: torchvision
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.05 # 1 machine
  BASE_LR_SCALE_NUM_SHARDS: True
  MAX_EPOCH: 20
  LR_POLICY: cosine
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 35.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 94
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 2
RNG_SEED: 3407

TENSORBOARD:
  ENABLE: True
  LOG_DIR: tensorboard/log
  # Leave empty to use cfg.OUTPUT_DIR/runs-{cfg.TRAIN.DATASET} as path.
  CLASS_NAMES_PATH: tensorboard/class_name_last.json
  # Path to json file providing class_name - id mapping.
  CATEGORIES_PATH: tensorboard/parent_child_last.json
  CONFUSION_MATRIX:
    ENABLE: True
    SUBSET_PATH: tensorboard/subset_last.txt
    # Path to txt file contains class names separated by newline characters.
                 # Only classes in this file will be visualized in the confusion matrix.
  HISTOGRAM:
    ENABLE: True
    TOPK: 5   
    # Top-k most frequently predicted classes for each class in the dataset.
    SUBSET_PATH: tensorboard/subset_last.txt
    # Path to txt file contains class names separated by newline characters.
                 # Only classes in this file will be visualized with histograms.

OUTPUT_DIR: result/X3D/
